### import pands as np

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('1. Weather Data.csv')
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

### Analyze dataframes
##### head

In [3]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

##### shape

In [4]:
data.shape

(8784, 8)

##### index

In [5]:
data.index

RangeIndex(start=0, stop=8784, step=1)

##### columns

In [7]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

##### dtype

In [8]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

##### unique

In [10]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

##### nunique

In [11]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

##### count

In [12]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

##### value_count

In [13]:
data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Drizzle,Haze                         3
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain,Snow Grains                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

##### info

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

### All unique 'Wind Speed'

In [16]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

### number of time when the 'Weather is exactly Clear'

###### value count

In [17]:
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Drizzle,Haze                         3
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain,Snow Grains                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Name: Weather, dtype: int64

###### filltering

In [18]:
data[data.Weather == 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

###### groubby()

In [20]:
data.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

### number of time when the 'Wind Speed was exactly 4km/h'

In [21]:
data[data['Wind Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

### the null values in the data

In [22]:
data.isnull()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

### Rename the column name 'Weather' of the dataframe to 'Weather Condition'

In [23]:
data.rename(columns = {'Weather' :' Weather Coundition'})

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Coundition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

### avrage of visbibility

In [25]:
data.Visibility_km.mean()

27.66444672131151

### standard deviation of 'Pressure '

In [30]:
data.Press_kPa.std()

0.8440047459486474

### variance of "Rel Hum_%"

In [31]:
data['Rel Hum_%'].var()

286.2485501984998

### instances when Wind Speed is above 24

In [39]:
data[(data['Wind Speed_km/h'] > 24) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

### mean value of 'Wind Speed_km/h'

In [41]:
data.groupby('Wind Speed_km/h').mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Visibility_km,Press_kPa
Wind Speed_km/h,,,,,
0,7.761165,2.840129,73.029126,25.539806,101.335340
2,3.500000,-3.100000,62.000000,17.700000,102.610000
4,7.022363,2.012869,72.833333,25.263080,101.438671
6,8.296552,2.860263,70.756979,27.200493,101.378473
7,8.838848,3.289808,70.487445,26.983752,101.307888
9,9.634096,3.680120,68.584337,27.754217,101.261675
11,10.163211,3.626802,66.405815,28.338812,101.186852
13,10.854014,4.054014,65.529252,28.190612,101.169782
15,10.500974,3.886370,66.382476,28.435466,101.065480
17,10.425676,3.830781,65.968468,28.942192,100.983649
19,8.745617,2.237662,66.285714,27.533279,100.909740
20,8.235887,1.516734,65.207661,28.676008,100.940665
22,8.602050,1.640774,64.480638,28.599089,100.813349
24,7.216310,0.389572,64.754011,28.996791,100.792834
26,6.313223,-0.761983,63.020661,29.699587,100.711653
28,6.358049,-0.611220,63.882927,28.165366,100.611073
30,6.350932,-0.700000,63.478261,27.929814,100.603789
32,4.798561,-1.305036,67.251799,26.234532,100.495252
33,5.690588,0.075294,69.047059,22.176471,100.206118
35,5.330189,0.003774,70.641509,21.477358,100.193774
37,5.066667,-0.088889,70.933333,23.582222,100.187778
39,3.408333,-0.916667,74.208333,18.404167,100.013333
41,5.413636,1.727273,78.863636,21.731818,99.635455
43,3.815385,-1.330769,70.153846,23.507692,99.854615
44,6.492857,1.628571,72.571429,22.928571,100.008571
46,1.572727,-1.172727,82.181818,15.854545,99.355455
48,6.053846,0.676923,69.923077,25.553846,99.707692
50,9.300000,2.875000,64.750000,30.825000,99.177500
52,5.014286,0.900000,75.142857,22.457143,99.817143
54,14.100000,10.000000,76.000000,25.000000,99.330000
57,2.080000,-5.420000,58.400000,29.480000,99.082000
63,5.000000,-5.000000,48.000000,48.300000,98.670000
70,0.500000,-4.000000,72.000000,25.000000,98.620000
83,3.700000,-2.100000,66.000000,25.000000,98.360000

### min & max Wind Speed_km/h

In [42]:
data.groupby('Wind Speed_km/h').min()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Visibility_km,Press_kPa,Weather
Wind Speed_km/h,,,,,,,
0,1/15/2012 4:00,-21.0,-26.6,21,0.2,99.14,Clear
2,11/14/2012 10:00,2.4,-4.3,61,11.3,101.88,Clear
4,1/1/2012 0:00,-20.7,-26.1,28,0.2,99.11,Clear
6,1/1/2012 3:00,-21.3,-26.5,22,0.6,98.07,Clear
7,1/1/2012 11:00,-23.3,-28.5,21,0.6,98.32,Clear
9,1/1/2012 10:00,-22.8,-28.0,27,0.8,98.64,Clear
11,1/11/2012 10:00,-21.2,-26.8,20,0.6,98.06,Clear
13,1/1/2012 13:00,-19.9,-26.0,18,0.6,98.10,Clear
15,1/1/2012 18:00,-18.1,-24.6,19,1.2,97.58,Clear
17,1/10/2012 17:00,-18.3,-25.1,23,1.0,98.39,Clear
19,1/1/2012 20:00,-18.0,-24.3,20,1.0,97.97,Clear
20,1/1/2012 14:00,-17.9,-25.3,24,1.0,97.99,Clear
22,1/1/2012 15:00,-18.0,-23.9,18,1.2,97.64,Clear
24,1/1/2012 22:00,-17.3,-25.4,23,1.0,98.07,Clear
26,1/10/2012 13:00,-16.8,-23.4,26,0.8,98.32,Clear
28,1/10/2012 3:00,-12.5,-22.8,21,1.0,97.75,Clear
30,1/1/2012 23:00,-15.8,-24.1,22,1.2,97.79,Clear
32,1/12/2012 11:00,-14.2,-21.9,21,1.2,97.81,Clear
33,1/12/2012 13:00,-13.7,-20.3,29,0.6,98.03,Clear
35,1/10/2012 1:00,-11.2,-17.2,27,1.2,97.98,Cloudy
37,1/13/2012 21:00,-12.4,-17.8,41,0.6,97.52,Cloudy
39,1/14/2012 0:00,-11.1,-17.7,56,0.6,98.61,Cloudy
41,1/24/2012 5:00,-5.9,-7.8,43,0.6,98.16,Cloudy
43,1/18/2012 9:00,-11.2,-17.2,51,1.2,97.93,Cloudy
44,1/2/2012 9:00,-6.5,-8.1,45,1.2,98.92,Cloudy
46,1/18/2012 5:00,-7.7,-12.4,62,0.6,97.56,Cloudy
48,1/18/2012 4:00,-6.1,-10.9,42,0.6,98.68,Cloudy
50,10/29/2012 19:00,3.2,-4.0,49,25.0,98.73,Cloudy
52,1/28/2012 23:00,0.3,-5.8,63,16.1,99.23,Cloudy
54,10/29/2012 23:00,14.1,10.0,76,25.0,99.33,Cloudy
57,1/18/2012 3:00,-3.5,-8.2,45,24.1,98.67,Mainly Clear
63,3/3/2012 16:00,5.0,-5.0,48,48.3,98.67,Mainly Clear
70,1/18/2012 2:00,0.5,-4.0,72,25.0,98.62,Mostly Cloudy
83,1/18/2012 1:00,3.7,-2.1,66,25.0,98.36,Mostly Cloudy

In [43]:
data.groupby('Wind Speed_km/h').max()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Visibility_km,Press_kPa,Weather
Wind Speed_km/h,,,,,,,
0,9/7/2012 18:00,28.0,20.5,100,48.3,103.63,Thunderstorms
2,11/20/2012 12:00,4.6,-1.9,63,24.1,103.34,Cloudy
4,9/7/2012 20:00,31.2,22.0,100,48.3,103.51,"Thunderstorms,Rain"
6,9/9/2012 6:00,27.3,20.8,99,48.3,103.46,"Snow,Haze"
7,9/9/2012 7:00,30.8,22.2,99,48.3,103.65,"Thunderstorms,Rain Showers,Fog"
9,9/9/2012 22:00,31.1,22.3,100,48.3,103.65,"Thunderstorms,Heavy Rain Showers"
11,9/9/2012 5:00,31.2,21.1,100,48.3,103.27,"Thunderstorms,Rain Showers"
13,9/8/2012 9:00,32.5,24.4,100,48.3,103.39,"Thunderstorms,Rain Showers"
15,9/9/2012 23:00,32.5,21.0,100,48.3,103.51,"Thunderstorms,Rain Showers"
17,9/9/2012 9:00,32.8,23.1,99,48.3,103.25,"Thunderstorms,Rain Showers,Fog"
19,9/9/2012 14:00,32.5,22.2,99,48.3,103.30,"Thunderstorms,Rain,Fog"
20,9/9/2012 4:00,32.6,21.1,98,48.3,103.21,"Thunderstorms,Rain Showers"
22,9/9/2012 16:00,33.0,22.6,97,48.3,102.90,"Thunderstorms,Rain Showers"
24,9/9/2012 2:00,33.0,23.2,97,48.3,103.19,"Thunderstorms,Rain Showers"
26,9/29/2012 16:00,32.2,22.9,93,48.3,103.18,"Snow,Fog"
28,9/9/2012 1:00,32.7,22.0,95,48.3,102.46,"Snow,Blowing Snow"
30,9/9/2012 0:00,32.1,20.2,94,48.3,102.18,"Thunderstorms,Rain Showers"
32,9/25/2012 9:00,30.7,21.8,96,48.3,102.32,"Thunderstorms,Rain Showers"
33,9/8/2012 17:00,29.9,18.4,94,48.3,102.13,"Snow,Ice Pellets"
35,9/8/2012 11:00,28.5,18.9,96,48.3,101.93,"Thunderstorms,Rain Showers,Fog"
37,9/8/2012 19:00,28.6,18.2,93,48.3,102.07,"Snow,Blowing Snow"
39,9/8/2012 18:00,26.1,18.2,92,25.0,102.03,"Snow,Blowing Snow"
41,8/30/2012 22:00,27.4,16.5,93,48.3,101.51,"Snow,Blowing Snow"
43,9/8/2012 20:00,25.5,16.3,92,48.3,101.42,Snow
44,9/8/2012 21:00,24.5,15.6,92,48.3,101.50,Snow
46,4/23/2012 5:00,10.5,7.8,92,25.0,100.73,"Snow,Blowing Snow"
48,4/23/2012 8:00,15.2,10.0,91,48.3,101.32,"Snow,Blowing Snow"
50,3/3/2012 20:00,14.2,9.8,75,48.3,99.65,Mostly Cloudy
52,4/23/2012 6:00,14.6,10.4,84,25.0,100.21,"Rain,Snow"
54,10/29/2012 23:00,14.1,10.0,76,25.0,99.33,Cloudy
57,3/3/2012 22:00,5.3,-3.4,70,48.3,99.96,Snow
63,3/3/2012 16:00,5.0,-5.0,48,48.3,98.67,Mainly Clear
70,1/18/2012 2:00,0.5,-4.0,72,25.0,98.62,Mostly Cloudy
83,1/18/2012 1:00,3.7,-2.1,66,25.0,98.36,Mostly Cloudy

### show all recordes were Weather Wind Speed_km/h is fog

In [46]:
data[data['Weather'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

### Find all instances when 'Weather is Clear' or 'Visibility is above 40'.

In [55]:
data[(data['Weather'] == 'Clear') | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

### 'Visibility is above 40'

In [56]:
data[(data['Weather'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear